CREATE DATABASE IF NOT EXISTS Vigil_DB;

USE Vigil_DB;

CREATE TABLE IF NOT EXISTS Agents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(45) NOT NULL UNIQUE,
    last_heard_time DATETIME
);

CREATE TABLE IF NOT EXISTS Alerts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ingest_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agent_id INT NOT NULL,
    alert_time DATETIME NOT NULL,
    message TEXT,
    CONSTRAINT FK_Alerts_Agents FOREIGN KEY (agent_id) REFERENCES Agents(id) ON DELETE CASCADE
);